AllCops:
  RunRailsCops: true
  Exclude:
    - sweet_notifications.gemspec
    - lib/sweet_notifications/version.rb
    - "vendor/**/*"
    - "gemfiles/vendor/**/*"

ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Documentation:
  Include:
    - lib/**/*.rb

MethodLength:
  Exclude:
    - lib/sweet_notifications/controller_runtime.rb

ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
