require: rubocop-rails

AllCops:
  Exclude:
    - sweet_notifications.gemspec
    - lib/sweet_notifications/version.rb
    - "vendor/**/*"
    - "gemfiles/vendor/**/*"
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Rails/AssertNot:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Include:
    - lib/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/sweet_notifications/controller_runtime.rb

Style/ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/SwapValues:
  Enabled: true
