require: rubocop-rails

AllCops:
  Exclude:
    - sweet_notifications.gemspec
    - lib/sweet_notifications/version.rb
    - "vendor/**/*"
    - "gemfiles/vendor/**/*"
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/AssertNot:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Documentation:
  Include:
    - lib/**/*.rb

MethodLength:
  Exclude:
    - lib/sweet_notifications/controller_runtime.rb

ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
