require: rubocop-rails

AllCops:
  Exclude:
    - sweet_notifications.gemspec
    - lib/sweet_notifications/version.rb
    - "vendor/**/*"
    - "gemfiles/vendor/**/*"
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Rails/AssertNot:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Include:
    - lib/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/sweet_notifications/controller_runtime.rb

Style/ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
