language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - Gemfile
rvm:
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
  - '2.6.0'
  - jruby-9.2.5.0
matrix:
  include:
    - rvm: '2.3.8'
      gemfile: 'gemfiles/rails_4.0.gemfile'
    - rvm: '2.3.8'
      gemfile: 'gemfiles/rails_4.1.gemfile'
    - rvm: '2.3.8'
      gemfile: 'gemfiles/rails_4.2.gemfile'
    - rvm: '2.6.0'
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
